---
- name: upgrade linux
  include: upgrade.yml
- name: install packages
  include: packages.yml
- name: copy conf files
  include: confs.yml
- include: site.yml
- name: restart everything
  include: restart_services.yml
